### ISSUE TITLE
Add self-CI

### ISSUE THREAD

**Issue by staticfloat** [thazhemadam/ytt-buildkite-plugin#2]
We should follow the example set by [`julia-buildkite-plugin` and set up self-CI](https://github.com/JuliaCI/julia-buildkite-plugin/blob/ced91aedc51b4e28830a59f8cfc40fd5dcfc2346/.buildkite/run_tests.yml).

We should run for the following configurations at first:

* x86_64-linux-gnu
* x86_64-apple-darwin
* aarch64-apple-darwin
* x86_64-w64-mingw32

It should be fairly straightforward to setup a templating system; unfortunately buildkite's `matrix` setup doesn't work with plugin attributes (😱), so we will need to instead do something like what the [`julia-buildkite-plugin` does and manually export bash variables](https://github.com/JuliaCI/julia-buildkite-plugin/blob/ced91aedc51b4e28830a59f8cfc40fd5dcfc2346/.buildkite/pipeline.yml#L6-L27) that are then used in our workhorse test runner.

One strange detail about self-testing is that, in order to properly use the current repository as a plugin within a pipeline, we have to install it into the "vendored plugin" location, which means that we add [these steps](https://github.com/JuliaCI/julia-buildkite-plugin/blob/ced91aedc51b4e28830a59f8cfc40fd5dcfc2346/.buildkite/run_tests.yml#L1-L4) as a [`metahook` plugin invocation](https://github.com/JuliaCI/julia-buildkite-plugin/blob/ced91aedc51b4e28830a59f8cfc40fd5dcfc2346/.buildkite/run_tests.yml#L13-L14) to all of our steps.  That allows us to [then use a relative path as a plugin source](https://github.com/JuliaCI/julia-buildkite-plugin/blob/ced91aedc51b4e28830a59f8cfc40fd5dcfc2346/.buildkite/run_tests.yml#L15-L16).

**Comment by thazhemadam** [comment]
Thanks for opening this issue, I was also wondering what the next step with regards to testing would be.
I had seen [`julia-buildkite-plugin`'s self-CI](https://github.com/JuliaCI/julia-buildkite-plugin/blob/ced91aedc51b4e28830a59f8cfc40fd5dcfc2346/.buildkite/run_tests.yml) setup, but wasn't sure how it could be actually implemented here, since I (in the context of this public repository) don't suppose I have access to any machines configured to run as buildkite agents.
